cpp_quote("hello \"world");

[local, uuid(4c75ddae-d485-11dd-96dc-0016cbce1b6a), version(1.0)]
interface CoTypes
{
	cpp_quote("/* All of the below are excluded from compilation -- they exist solely");
	cpp_quote(" * for the benefit of the IDL compiler. The real definitions come from");
	cpp_quote(" * COM/COM.h.");
	cpp_quote(" */");
	cpp_quote("# if 0");
	
	typedef unsigned long long uint64_t;
	typedef long long int64_t;
	typedef unsigned long uint32_t;
	typedef long int32_t;
	typedef unsigned short uint16_t;
	typedef short int16_t;
	typedef unsigned char uint8_t;
	typedef signed char int8_t;
	
	typedef struct tagTEST {
		uint32_t len;
		const char foo;
		struct foobar *const p;
		struct {
			char a;
			uint64_t b;
		} baz;
		int (*funcptr)(int int_arg1, const char *str_arg2);
	} test_struct_t;
		
	cpp_quote("# endif /* 0 */");
	
	int hello();
	
}

